version: "3.8"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_container
    ports:
      - "81:81"
    restart:
      unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - home_away.env
    volumes:
      - .:/app
      - ./images:/images

  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - home_away.env
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
