
USER_ID_LEN = 32
USER_ID_REGEX = f"^[a-f0-9]{{{USER_ID_LEN}}}$"


USER_EMAIL_MAX = 100
USER_EMAIL_REGEX = "^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$"



USER_USERNAME_MIN = 2
USER_USERNAME_MAX = 20
USER_USERNAME_REGEX = f"^[a-zA-Z0-9]{{{USER_USERNAME_MIN-1},{USER_USERNAME_MAX-1}}}$"


USER_FIRST_NAME_MIN = 2
USER_FIRST_NAME_MAX = 20
USER_FIRST_NAME_REGEX = f"^[a-zA-ZæøåÆØÅ][a-zA-ZæøåÆØÅ\-\s]{{{USER_FIRST_NAME_MIN-1},{USER_FIRST_NAME_MAX-1}}}$"


USER_LAST_NAME_MIN = 2
USER_LAST_NAME_MAX = 20
USER_LAST_NAME_REGEX = f"^[a-zA-ZæøåÆØÅ][a-zA-ZæøåÆØÅ\-\s]{{{USER_LAST_NAME_MIN-1},{USER_LAST_NAME_MAX-1}}}$"


USER_PASSWORD_MIN = 6
USER_PASSWORD_MAX = 50
USER_PASSWORD_REGEX = f"^.{{{USER_PASSWORD_MIN-1},{USER_PASSWORD_MAX-1}}}$"

ITEM_NAME_MIN = 1
ITEM_NAME_MAX = 100
ITEM_NAME_REGEX = f"^[a-zA-Z0-9\søæåØÆÅ]{{{ITEM_NAME_MIN-1},{ITEM_NAME_MAX-1}}}$"

STAR_MIN = 1
STAR_MAX = 5
ITEM_STARS_REGEX = f"^[{STAR_MIN}-{STAR_MAX}]$"

ITEM_IMAGE_REGEX = "^.*\.(jpg|jpeg|png|gif|webp)$"

ITEM_LATLON_REGEX = "^-?\d{1,3}\.\d+$"

ITEM_PRICE_REGEX = "^\d+(\.\d{1,2})?$"

NIGHT_MIN = 1
NIGHT_MAX = 30